spring:
  security:
    oauth2:
      authorizationserver:
        client:
          auth-client:
            registration:
              client-id: "auth"
              client-secret: "{noop}secret"
              client-authentication-methods:
                - "client_secret_basic"
              authorization-grant-types:
                - "authorization_code"
                - "refresh_token"
                - "client_credentials"
              redirect-uris:
                - "http://GATEWAY-SERVICE:1004/login/oauth2/code/auth"
              post-logout-redirect-uris:
                - "http://GATEWAY-SERVER:1004/logged-out"
              scopes:
                - "openid"
                - "profile"
                - "auth.user.all"
                - "auth.user.read"
                - "auth.user.write"
                - "auth.admin"
            require-authorization-consent: true

server:
  port: 8081

