server:
  port: 1004
# eureka:
#   client:
#     service-url:
#       default-zone: http://localhost:8761/euraka/spring:
spring:
  security:
    oauth2:
      client:
        registration:
          auth:
            provider: spring
            client-id: auth
            client-secret: secret
            authorization-grant-type: authorization_code
            scope: openid,profile,auth.user.all,auth.user.read,auth.user.write,auth.admin
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          spring:
            issuer-uri: http://localhost:8081
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: test-service
              uri: http://localhost:8082
              predicates:
                - Path=/test/**
              filters:
                - StripPrefix=1
                - TokenRelay=

